### ISSUE TITLE
Is it supposed to move? 

### ISSUE THREAD

**Issue by GoogleWasAllMyIdea** [Ariakim-Taiyo/GeoFs-ILS#1]
It just stays frozen I tried landing at Miami intl and it wasn't moving or showing anything. I purposefully landed off course but it said I was on the centerline and never changed.

**Comment by Ariakim-Taiyo** [comment]
Be sure to keep the console open. Also, it is possible that you were using an old revision from this morning. I fixed an issue with multi runway support recently.

**Comment by GoogleWasAllMyIdea** [comment]
oke
