### ISSUE TITLE
bookmark script does not work.

### ISSUE THREAD

**Issue by iL0g1c** [Ariakim-Taiyo/GeoFs-ILS#2]
I pasted the code into a new bookmark and activated it, but nothing happened. Is there something that I am doing wrong?

**Comment by Ariakim-Taiyo** [comment]
the bookmark script is deprecated, instead make a new bookmark with the following:
` javascript:(function()%7B(function() %7Bvar x %3D document.createElement("script")%3Bx.src %3D "https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2FSnowLord7%2Fdevconsole%40master%2Fmain.js"%3Bx.onload %3D alert("Loaded Developer Console!")%3Bdocument.head.appendChild(x)%3B%7D)()%7D)()`

click on the bookmark and paste the normal code into the replacement console.

**Comment by iL0g1c** [comment]
Thank you!
